version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      # MINDSERS- ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./etc/nginx/ssl/live/dev.fomotools.live/fullchain.pem:/etc/nginx/ssl/live/dev.fomotools.live/fullchain.pem
      - ./etc/nginx/ssl/live/dev.fomotools.live/privkey.pem:/etc/nginx/ssl/live/dev.fomotools.live/privkey.pem
      
    networks:
      - web_network
    depends_on: 
      - appseed-app
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appseed_db
      MYSQL_USER: appseed_db_usr
      MYSQL_PASSWORD: pass
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./fomotoolsdbdata/db:/var/lib/mysql
    networks:
      - db_network
volumes:
  mysql_data:
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
