# This is a basic workflow to automate application deployment everytime somebody pushed on the devevelop remote repository branch 

name: Fomotools x AppSeed CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: 167.86.74.118
        username: Fomotools
        key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBPqioKpv
fXvlaqqJjS6jC8AAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIK4o5zocS3jJ9Q1E
BE4NMQj8BGFa5ea7s1glECXF9A4HAAAAoGy6JexrUwM8GxdlzZurlU9bdTAHH/oDmLnZyK
A3EGr5h586kvSEObiK3AcRXSwxpSVqB0ua1EtHZxenDWq8hoj8g8NcYbADfr4ZcRpN4fsO
UYfJTq77cSBfA9W1VC3B14viP711e+3WR+l0T1cdxy7ZP2+PcAlp4Sq1s2u8qOCj/q/qOe
a8B95ft7z+cI7EMd93kfDGSCRV06yfhaDOtFI=
-----END OPENSSH PRIVATE KEY-----
        port: 22
        passphrase: taplecod
        script: |
          echo "triggered" >> ../githubactions.log
          cd ~/FomoTools/
          git pull
          git status
          docker-compose up --build