# This is a basic workflow to automate application deployment everytime somebody pushed on the devevelop remote repository branch 

name: Fomotools x AppSeed CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: 167.86.74.118
        username: Fomotools
        key: -----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,3AF6BC47A50F4AE816B6B09FBA59E4B7

4RWgzw0XZ05d+4VUgdG+wTSj4GTfDYx5K/wqnMNPXNe/vaTcT0o7BW2Kesruh1Kf
82r0oXkQudg6u24OXhEyOyYibROWzcVIey1Qaaf3yG3veEakhbp5EHk56T89wOCB
VO9JrcSgUWuUMMWLBzbZbqryvlo+f6x4cCl1whtv/vSv756bjzUETYT2SuLiMgdK
8KXMOVI0a1lxAlzRBSc6u5mjWu8kAcgr4gVw0PvGOjKLm5A0eD0urji5TXclkjMu
6g9Lv6t+niGs3mLFnfCPiydFcWqZYbAa6q4MlL14BphQueyMg0DpHTjBjm8V23XZ
OIQ2CIBQKIGCZlMiX9wV+A/VtUfEf3d0Ym08HPSL36bqs9JuouZRxUQSQnR1TOFY
Q5K3ljM23hDMFOvrbJ1IQGjABoHlIlUKe/YexNxUv+GmRk5p1aOt54u286+QrFP8
ISEZoEnvZpU8JB5bp+S1Cf3eNjZaPtfGiYOs2c2Qn0s+TA9QIvxKZVUhbvUIPUvv
AQyl77TRr1B/Pt9JAp4ADlz53EvE8mnHFa39oGR7BTTBbmjfv1w4l3GvDrTM0V7Y
Cn8pO2U2WuBXThW9W4WV0m39w0vLXuD4JQvsJC4ve51FrSeN2npTh4lPRY6BTROO
pe1sRHN84O9cmXtMsz/TtIhG4lmbl0hlXhRTvihsaDvNpmGx958FTlImy0S9qqJ8
rQVNI9uknydFsJRvRgWaG9T4IbXYZVDuV1LPNCjSYKKW+/+WuXhSdMnVeoA8jeHt
03GgyiYzqBPfqIHz060Fc0nPhvuVfAzXJmhN5lWhiHxXOeTbybfC/HnlG4kGnTCv
LQyMi1LmiAO2MErganyxWUVO4ENaBfNDyvOLSV3t6gNfHAyvf7WO8JHeefQPlgX1
J3PuEjeXTtyYi0jpQQkgSQjpHcx1VKo9NWWKnhQ4ydp2NExF8LxQNwUEbnZzGZ4V
P6UwF8483JFR1s1r9fuCCXg5ZlSH5NdqLm9AUzG6vZ5ctKg74seGsstEUZCBleuX
EfERWdxNCq9R2jeA545vfKy44tDTIHy8bB2LHTv3VNSv53Td8LAf2bp8vClCGqWQ
6frwPWm/3W/pxeD7kSzj5bmicqJh1kKL3hivmAtHNcAXHZwlG2X6CFW+FUaG3637
CS1gnVg4sImqn8FFnBKzVbQzCGMnN0N6SKogY7SekcsIg/0QBbi6Aq8lVcbEmNFj
VUUeyuxBctz4CrazAqmpa3ohaXB/1KrNe38jjxzZpjHfPa6gJmvrRASDe37l7Ncg
3fBtKQmEsKgEFGXiH3K3C3Xs7XpHl1Ggo70tMlSEXKsZ8Ryluc1pPGm18zBedO+t
B780UqsuUogEtywxRy90VX8+q1/aK74khwMI739LjWc5uTgEaw/QHngOYYzWVex+
BiQmPkvRLqJbJg4bxMMF90mT1dF66Awlced0fgIG2e7yf3+srmm8JN2OxhpTlDTn
uihUHQK4m+mgl4Zk0M0mHOBO8JCoUiklQqxGuu8LRs2EeewChsyuTbEjbqueJ+D+
dVT439grKkVr+QmZ8jcVhpPEJpXy3ePEOqn7c/CmQx5kOIsjPIU0aWysYjXK9msG
mSrg8RDECmBA7Q79ncw+a7O3PIcngLJNyGc0Oc27rTI4Iz+0Fm5gBOQIT95csozV
k/3NAVrnsT3iEO0IhF8r5wEwtUUfTraIVwCkeL0AFRlgpQmnu8h4AdtFBEl5G/l2
71MJ6UiZaU/MBmQJ8AlSUivow6+PFwoE9vTa2k59qGIqN50aDtjomYrKUnH3/Zkm
VutAxcf/NjkW4jytSGpC2ywe8S1IvpL7bqFNWO4gKH9z/tOneiW34dDzzPHrblvU
lnTodNfxswTYPB0xpCGegXNr8Xu7DXkbtz1EnrXRAU24oZryewhziJguxIy55dsr
4A+t3y0twahxSSXLN9eS0rRObQZtDWnWHnupDQbuGEBE3l5kNRirtxBCnHT8o2my
MmHfjlkenrDt5uT0FrXDjOY2USIONi6V7lQvLH+lSqfZ0EOMn721TT39s7tu4SZH
WYM4Hf0n7rLch8nRiYrUAwpkJr55hm38wBESIAN2X71R9ssTKGglM//22B8knZXq
U4tIC1YE+DsAi7+aTl6iSXTKU68qMjFy75IMqg9iznb9bDaCdJ9aGUtn/+g/TvTS
+RdbK1Wue3ERXmnO586XHNYew6X/DragG5dAnW/Ija3Kc0pvZukMSKWmVCmEKyD2
v8A2oiwHgjeWXle+LRLVdOPplSX2TXZswE0EvQL5GpW3IcIPMPnl1byEo3ZD+xk5
gKLy2irSiFfP3XnrmCiifFAwe7EutvZWxnKeP9JY8GSMYsTHmjGMW4Eb91H8uA/x
xNBzmCR463+Lr/dwirRqdn+DK56VcIbQG8gO1P30cYz1KLqDOReLxKApELzNyXFb
zeBph3nnWIFjNnR54vI8AD+cJb6B+66avZT8l4PhbPzq95gHPbiHSS/iYJSSiXFE
2nQpmMa0wrYK0lGqGhHPbArZxZTyou/ZigPpYMlFmOaHoNEyCsLYfw532fC+lNjW
zYEAD8BgJlfnvj8bqGuJ1ZG4hPLg0poTXIyumRA1GKFgJkx5PWAzVGqUuovZocQQ
5+RMm0j4uC/n9c9u/TOg3uBDONHrlBKTqeMSJa9N0zgd0Xe+grj6MGYu1Zupr3sp
3cPvgrtViQhXQi5HTakDaERWVl7UuQCd/kUWkd8gQuieW2aK9Z+WdhjFMa3bKQMC
8e4KAJ6ym95klmuZBwvcJ7q8iHu91Ia13/gP8wBdpIwiv07eQ0Zsv5j/RKOXfanj
vun8KKUf/dOIhSbklGJDcXJKqJKHuW00JsnCMfGs4UE8aliDemdF6utzEiHC04Fj
uuE8moA3WDpU+R6hklHvwm8k7W7ftdbGHMPikMhvQUPsBOvcIHlj7YjLUv6pqaNH
W/Ex6e72SklkQPq6o3RXv6QFTM+DnY0GAQx97BM2GyzFZ44kWzods6si6JMelIw5
QNOLmmS/tvUjvSBs7D6hiQHFn2YAQizbjreKpSidMr0E76RUY9axOfWiQCC6+bpk
W5WQ61jjF0pY+kq3dg233AN9TAWUJVDh5rBz6OeMlxE8ROBE+XohUCtjzaUhfO4s
-----END RSA PRIVATE KEY-----
        port: 22
        script: |
          echo "triggered" >> ../githubactions.log
          cd ~/FomoTools/
          git pull
          git status
          docker-compose up --build